name: Build website and deploy

on:
  push:
    branches: [ master ]

env:
  SCHEME: https://
  DOMAIN: mista.me

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.0.2'
        cabal-version: '3.8'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}
        restore-keys: ${{ env.cache-name }}-

    - name: Install dependencies
      run: cabal update && cabal build --only-dependencies

    - name: Compile website builder
      run: cabal build all

    - name: Build website
      env:
        WEBSITE_URL: ${{ env.SCHEME }}${{ env.DOMAIN }}
      run: cabal exec website rebuild

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
        cname: ${{ env.DOMAIN }}
