name: Build website and deploy

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: xom9ikk/dotenv@v2

    - uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.0.2'
        cabal-version: '3.8'

    - name: Initialize cabal
      run: |
        cabal update
        cabal clean
        cabal configure
        cabal freeze

    - name: Restore cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}-${{ github.sha }}
          ${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}-
          ${{ runner.os }}-

    - name: Install dependencies
      run: cabal build --only-dependencies

    - name: Compile website builder
      run: cabal build all

    - name: Build website
      env:
        WEBSITE_URL: ${{ env.SCHEME }}${{ env.DOMAIN }}
      run: cabal exec website rebuild

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _site
        cname: ${{ env.DOMAIN }}
