name: Build website and deploy

on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build packages
        run: nix build --no-link .#print-website-vars .#website

      - name: Reify website variables
        run: nix run .#print-website-vars >> $GITHUB_ENV

      - name: Run website builder
        run: nix run .#website rebuild

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          cname: ${{ env.WEBSITE_DOMAIN }}
